services:
  opensuivi:
    build: .
    container_name: opensuivi
    restart: unless-stopped
    ports:
      - "${PORT:-5050}:${PORT:-5050}"
    volumes:
      - opensuivi_data:/data
      - opensuivi_static:/app/static
    environment:
      - DATA_DIR=/data
      - PYTHONUNBUFFERED=1
      - PORT=${PORT:-5050}
      # - FLASK_DEBUG=false

volumes:
  opensuivi_data:
  opensuivi_static:
